!
! Zebra configuration saved from vty
!   2026/07/15 16:46:40
!
frr version 10.6.1
frr defaults traditional
!
hostname R3BGP
!
route-map ALLOW-ALL permit 10
exit
!
!
!
!
!
!
router bgp 300
 neighbor 10.0.1.1 remote-as 200
 !
 address-family ipv4 unicast
  network 172.16.30.0/24
  neighbor 10.0.1.1 route-map ALLOW-ALL in
  neighbor 10.0.1.1 route-map ALLOW-ALL out
 exit-address-family
!
exit
!
!
!
!
!
