!
! Zebra configuration saved from vty
!   2026/07/08 12:56:15
!
frr version 10.6.1
frr defaults traditional
!
hostname ubuntu-VirtualBox
!
!
!
!
!
!
interface veth-r3-r2
 ip ospf network point-to-point
exit
!
!
router ospf
 ospf router-id 3.3.3.3
 network 3.3.3.3/32 area 0
 network 10.0.23.0/30 area 0

exit
!
!
!
!
