!
! Zebra configuration saved from vty
!   2026/07/15 12:50:47
!
frr version 10.6.1
frr defaults traditional
!
hostname R2BGP
!
route-map ALLOW-ALL permit 10
exit
!
!
!
!
!
!
router bgp 200
 neighbor 10.0.0.1 remote-as 100
 neighbor 10.0.1.2 remote-as 300
 !
 address-family ipv4 unicast
  neighbor 10.0.0.1 soft-reconfiguration inbound
  neighbor 10.0.0.1 route-map ALLOW-ALL in
  neighbor 10.0.0.1 route-map ALLOW-ALL out
  neighbor 10.0.1.2 soft-reconfiguration inbound
  neighbor 10.0.1.2 route-map ALLOW-ALL in
  neighbor 10.0.1.2 route-map ALLOW-ALL out
 exit-address-family
!
exit
!
!
!
!
!
