!
! Zebra configuration saved from vty
!   2026/07/08 12:56:48
!
frr version 10.6.1
frr defaults traditional
!
hostname ubuntu-VirtualBox
!
!
!
!
!
!
interface veth-r1-r2
 ip ospf network point-to-point
exit
!
!
router ospf
 ospf router-id 1.1.1.1
 network 1.1.1.1/32 area 0
 network 10.0.12.0/30 area 0

exit
!
!
!
!
