!
! Zebra configuration saved from vty
!   2026/07/08 21:11:36
!
frr version 10.6.1
frr defaults traditional
!
hostname ubuntu-VirtualBox
!
!
!
!
key chain OSPF-SHA
 key 1
  cryptographic-algorithm hmac-sha-256
  key-string LabSecret2026
 exit
exit
!
!
!
interface veth-r4-r2
 ip ospf network point-to-point
 ip ospf authentication key-chain OSPF-SHA
exit
!
!
router ospf
 ospf router-id 4.4.4.4
 network 4.4.4.4/32 area 0
 network 10.0.24.0/30 area 0

exit
!
!
!
!
