frr version 10.6.1
frr defaults traditional
hostname R1BGP
!
route-map ALLOW-ALL permit 10
!
router bgp 100
 neighbor 10.0.0.2 remote-as 200
 !
 address-family ipv4 unicast
  neighbor 10.0.0.2 activate
  neighbor 10.0.0.2 route-map ALLOW-ALL in
  neighbor 10.0.0.2 route-map ALLOW-ALL out
 exit-address-family
exit
!
end
