!
! Zebra configuration saved from vty
!   2026/07/10 12:22:07
!
frr version 10.6.1
frr defaults traditional
!
hostname ubuntu-VirtualBox
!
!
!
!
!
!
interface veth-atk-r2
 ip ospf network point-to-point
exit
!
!
router ospf
 ospf router-id 9.9.9.9
 network 10.0.99.0/30 area 0
 default-information originate always

exit
!
!
!
!
