!
! Zebra configuration saved from vty
!   2026/07/10 12:22:06
!
frr version 10.6.1
frr defaults traditional
!
hostname ubuntu-VirtualBox
!
!
!
!
key chain OSPF-SHA
 key 1
  cryptographic-algorithm hmac-sha-256
  key-string LabSecret2026
 exit
exit
!
!
!
interface veth-r2-atk
 ip ospf network point-to-point
exit
!
!
interface veth-r2-r1
 ip ospf network point-to-point
 ip ospf authentication key-chain OSPF-SHA
exit
!
!
interface veth-r2-r3
 ip ospf network point-to-point
 ip ospf authentication message-digest
 ip ospf message-digest-key 1 md5 LabSecret2026
exit
!
!
interface veth-r2-r4
 ip ospf network point-to-point
 ip ospf authentication message-digest
 ip ospf message-digest-key 1 md5 LabSecret2026
exit
!
!
router ospf
 ospf router-id 2.2.2.2
 network 2.2.2.2/32 area 0
 network 10.0.12.0/30 area 0
 network 10.0.23.0/30 area 0
 network 10.0.24.0/30 area 0
 network 10.0.99.0/30 area 0

exit
!
!
!
!
