frr version 10.6.1
frr defaults traditional
hostname R4BGP
!
route-map ALLOW-ALL permit 10
!
router bgp 400
 neighbor 10.0.2.1 remote-as 200
 !
 address-family ipv4 unicast
  network 172.16.30.0/25
  neighbor 10.0.2.1 route-map ALLOW-ALL in
  neighbor 10.0.2.1 route-map ALLOW-ALL out
 exit-address-family
exit
!
end
