!
! Zebra configuration saved from vty
!   2026/07/15 18:22:21
!
frr version 10.6.1
frr defaults traditional
!
hostname R1BGP
!
route-map ALLOW-ALL permit 10
exit
!
route-map RPKI-SIM permit 10
 match ip address prefix-list ROA-AS300
exit
!
route-map RPKI-SIM deny 20
exit
!
!
!
!
!
!
router bgp 100
 neighbor 10.0.0.2 remote-as 200
 !
 address-family ipv4 unicast
  neighbor 10.0.0.2 route-map RPKI-SIM in
  neighbor 10.0.0.2 route-map ALLOW-ALL out
 exit-address-family
!
exit
!
ip prefix-list ROA-AS300 seq 10 permit 172.16.30.0/24
!
!
!
!
