!
! Zebra configuration saved from vty
!   2026/07/08 20:07:12
!
frr version 10.6.1
frr defaults traditional
!
hostname ubuntu-VirtualBox
!
!
!
!
key chain OSPF-SHA
 key 1
  cryptographic-algorithm hmac-sha-256
  key-string LabSecret2026
 exit
exit
!
!
!
interface veth-r1-r2
 ip ospf network point-to-point
 ip ospf authentication key-chain OSPF-SHA
exit
!
!
router ospf
 ospf router-id 1.1.1.1
 network 1.1.1.1/32 area 0
 network 10.0.12.0/30 area 0

exit
!
!
!
!
